services:
  postgres:
    image: postgres:16
    container_name: coreboard_postgres
    environment:
      POSTGRES_DB: coreboard_db
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - coreboard_data:/var/lib/postgresql/data

volumes:
  coreboard_data: