package com.coreboard.api.domain.dto.metrics;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;

import java.math.BigDecimal;
import java.util.UUID;

@Builder
@Schema(description = "Financial value and engagement metrics grouped by customer")
public record CustomerMetricsResponse(

        @Schema(description = "Customer ID")
        UUID customerId,

        @Schema(description = "Customer's name", example = "John Doe")
        String customerName,

        @Schema(description = "Total number of Service Orders requested by this customer", example = "5")
        Long totalOrders,

        @Schema(description = "Total financial value generated by this customer's requests", example = "4300.00")
        BigDecimal generatedValue
) {}