package com.coreboard.api.domain.dto.metrics;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;

import java.math.BigDecimal;
import java.util.UUID;

@Builder
@Schema(description = "Performance and productivity metrics grouped by employee")
public record EmployeeMetricsResponse(

        @Schema(description = "Employee ID")
        UUID employeeId,

        @Schema(description = "Employee's name", example = "Charles Technician")
        String employeeName,

        @Schema(description = "Total number of Service Orders assigned to this employee", example = "45")
        Long totalOrders,

        @Schema(description = "Total financial value generated by the employee's assigned orders", example = "12500.00")
        BigDecimal generatedValue,

        @Schema(description = "Total amount effectively received from the employee's completed orders", example = "11000.00")
        BigDecimal receivedValue
) {}